// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uC6C_jn4AwWpAf_IsYxhHKCwn1RVOac',
    appId: '1:783863143751:web:94a665af002257ca608062',
    messagingSenderId: '783863143751',
    projectId: 'sku-management-2d348',
    authDomain: 'sku-management-2d348.firebaseapp.com',
    storageBucket: 'sku-management-2d348.firebasestorage.app',
    measurementId: 'G-4Q6HNL83Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkJnVD_nrBkGgs4HPhPkaEp14HviInGm8',
    appId: '1:783863143751:android:514522b490951730608062',
    messagingSenderId: '783863143751',
    projectId: 'sku-management-2d348',
    storageBucket: 'sku-management-2d348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvxFUMgaibhYieJthGKqx9rRwA5UO4bs',
    appId: '1:783863143751:ios:6e7c92c12d07ebd9608062',
    messagingSenderId: '783863143751',
    projectId: 'sku-management-2d348',
    storageBucket: 'sku-management-2d348.firebasestorage.app',
    iosBundleId: 'com.example.sku',
  );
}
